<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class UserAgents extends BaseConfig
{
    public $platforms = [
        'windows nt 10.0' => 'Windows 10',
        'windows nt 6.3'  => 'Windows 8.1',
        'windows nt 6.2'  => 'Windows 8',
        'windows nt 6.1'  => 'Windows 7',
        'windows nt 6.0'  => 'Windows Vista',
        'windows nt 5.2'  => 'Windows 2003',
        'windows nt 5.1'  => 'Windows XP',
        'windows nt 5.0'  => 'Windows 2000',
        'windows nt 4.0'  => 'Windows NT 4.0',
        'winnt4.0'        => 'Windows NT 4.0',
        'winnt 4.0'       => 'Windows NT',
        'winnt'           => 'Windows NT',
        'windows 98'      => 'Windows 98',
        'win98'           => 'Windows 98',
        'windows 95'      => 'Windows 95',
        'win95'           => 'Windows 95',
        'windows'         => 'Unknown Windows OS',
        'android'         => 'Android',
        'blackberry'      => 'BlackBerry',
        'iphone'          => 'iOS',
        'ipad'            => 'iOS',
        'ipod'            => 'iOS',
        'os x'            => 'macOS',
        'ppc mac'         => 'Power PC Mac',
        'freebsd'         => 'FreeBSD',
        'ppc'             => 'Macintosh',
        'linux'           => 'Linux',
        'debian'          => 'Debian',
        'sunos'           => 'Sun Solaris',
        'beos'            => 'BeOS',
        'apachebench'     => 'ApacheBench',
        'aix'             => 'AIX',
        'irix'            => 'Irix',
        'osf'             => 'DEC OSF',
        'hp-ux'           => 'HP-UX',
        'netbsd'          => 'NetBSD',
        'bsdi'            => 'BSDi',
        'openbsd'         => 'OpenBSD',
        'gnu'             => 'GNU/Linux',
        'unix'            => 'Unknown Unix OS',
        'symbian'         => 'Symbian OS',
    ];

    public $browsers = [
        'OPR'   => 'Opera',
        'Flock' => 'Flock',
        'Edge'  => 'Spartan',
        'Edg'   => 'Edge',
        'Chrome' => 'Chrome',
        'Opera' => 'Opera',
        'MSIE'  => 'Internet Explorer',
        'Internet Explorer' => 'Internet Explorer',
        'Trident' => 'Internet Explorer',
        'Safari' => 'Safari',
        'Firefox' => 'Firefox',
        'MxBrowser' => 'Maxthon',
        'Konqueror' => 'Konqueror',
        'amaya' => 'Amaya',
        'omniweb' => 'OmniWeb',
        'Avant Browser' => 'Avant Browser',
        'Camino' => 'Camino',
        'Flock' => 'Flock',
        'AOL' => 'AOL Browser',
        'Lynx' => 'Lynx',
        'Shiira' => 'Shiira',
        'Netscape' => 'Netscape',
        'iCab' => 'iCab',
        'Links' => 'Links',
        'Lynx' => 'Lynx',
        'w3m' => 'w3m',
        'Safari iPhone' => 'Mobile Safari',
        'Safari iPad' => 'Mobile Safari',
        'Safari iPod' => 'Mobile Safari',
        'Chrome Mobile' => 'Chrome Mobile',
        'Firefox Mobile' => 'Firefox Mobile',
        'Opera Mobile' => 'Opera Mobile',
        'Opera Mini' => 'Opera Mini',
        'Mobile Safari' => 'Mobile Safari',
        'Android Browser' => 'Android Browser',
        'BlackBerry' => 'BlackBerry Browser',
        'BB10' => 'BlackBerry 10',
        'Palm' => 'Palm',
        'Silk' => 'Amazon Silk',
        'Nokia' => 'Nokia Browser',
        'UCBrowser' => 'UC Browser',
    ];

    public $mobiles = [
        'ipad' => 'iPad',
        'iphone' => 'iPhone',
        'ipod' => 'iPod',
        'kindle' => 'Kindle',
        'silk' => 'Silk',
        'android' => 'Android',
        'blackberry' => 'BlackBerry',
        'opera mini' => 'Opera Mini',
        'opera mobi' => 'Opera Mobi',
        'mobile' => 'Generic Mobile',
        'tablet' => 'Generic Tablet',
        'palm' => 'Palm',
    ];

    public $robots = [
        'googlebot' => 'Googlebot',
        'msnbot' => 'MSNBot',
        'baiduspider' => 'Baiduspider',
        'bingbot' => 'Bingbot',
        'slurp' => 'Inktomi Slurp',
        'yahoo' => 'Yahoo',
        'askjeeves' => 'Ask Jeeves',
        'fastcrawler' => 'FastCrawler',
        'infoseek' => 'InfoSeek Robot 1.0',
        'lycos' => 'Lycos',
        'yandex' => 'YandexBot',
        'mediapartners-google' => 'MediaPartners Google',
        'CRAZYWEBCRAWLER' => 'Crazy Webcrawler',
        'adsbot-google' => 'AdsBot Google',
        'feedfetcher-google' => 'Feedfetcher Google',
        'curious george' => 'Curious George',
        'ia_archiver' => 'Alexa Crawler',
        'MJ12bot' => 'Majestic SEO',
        'Uptimebot' => 'Uptime robot',
    ];
}

